### ISSUE TITLE
No way to get Stone Dust

### ISSUE THREAD

**Issue by woodrc** [breakinblocks/nutsandboltstorqued#128]
Unless I've missed it there is no way to get stone dust in the latest version. Recipes only exist from the later IC2 machines. If IC2:dust:15 is the correct identifier there is no mention in the AE2 minetweaker recipe.

**Comment by Saereth** [comment]
squeezer rocky combs from rock hives, although I am planning to get the recipe working for ae2 grindstone soon hopefully for the next update.

**Comment by Saereth** [comment]
smelting stone will give stone dust next update

**Comment by hirnstrudel** [comment]
In 1.6.4.7 smelting stone now gives you a circuit plate from Project Red.
So still no stone dust ;)

**Comment by Saereth** [comment]
This was technically fixed, and then unfixed by adding project red! Will fix it up next time :P Squeezer can still get it in the meantime from rock hives. Im also reducing the quest to 1 instead of 10 dust.

**Comment by implayin** [comment]
You can craft the Ore Washing Plant by putting in Gravel and you don't need stone dust for it.

**Comment by it-is-I-Pants** [comment]
made a minetweaker script to fix this just rename the file back to .zs to use it
[stonedustfix.txt](https://github.com/breakinblocks/nutsandboltstorqued/files/962954/stonedustfix.txt)

**Comment by it-is-I-Pants** [comment]
woops, my bad I forgot to adjust some things back on the script when I was testing things. I meant to make it all use cobblestone but I had cobble set for the hammer recipe and smoothstone for the crusher. it's fixed here to use cobble 
[stonedustfix.txt](https://github.com/breakinblocks/nutsandboltstorqued/files/962965/stonedustfix.txt)

**Comment by Saereth** [comment]
Im gonna use that hammer recipe, sadly the AA crusher is not intended to be enabled, that somehow got added back in when Actually additions was updated and the configs got rebuilt so next update it will be removed again. Early game doing it with the hammer seems like a good solution, then people can move on to doing it with the orewashing plant as thats just a tier 1 machine. The quest is also being reduced to 1 dust instead of 10.

**Comment by it-is-I-Pants** [comment]
hmm, the orewashing plant only gives 1 per irrc, i think i would be able to swap out the aa crusher for the ie crusher if that works out better. I don't know about other people, but I like to build with reinforced stone quite a bit. That is, unless you're using it to gate something else, I haven't checked.

**Comment by Saereth** [comment]
yep IE crusher works, will add it! This is all fixed in the update coming out this weekend now

**Comment by Electrofried** [comment]
The recipe for <ic2:dust:15> is still not in the newest version and can only be obtained by using the bee method.
